### ISSUE TITLE
Android: Notification destroyed when application move to background

### ISSUE THREAD

**Issue by AshfaqMemon** [ghenry22/cordova-plugin-music-controls2#7] opened 2019-11-03 10:53 UTC
Hi

I am using this plugin in ionic 2 application. I am calling create method once my audio is loaded completely. I am able to create the music controls notification with the necessary data when application is in front end, but when application moves to back ground, notification automatically disappears. Also, I have observed that when the second song loads in background the updated notification appears itself.

This is my sample code snippet:

    let musicControllOptions = {
            track: this.trackToPlay.title,
            artist: this.trackToPlay.artist,
            cover: this.trackToPlay.art,      // optional, default : nothing
            isPlaying: false,                         // optional, default : true
            dismissable: false,                         // optional, default : false
            // hide previous/next/close buttons:
            hasPrev: true,      // show previous button, optional, default: true
            hasNext: true,      // show next button, optional, default: true
            hasClose: true,       // show close button, optional, default: false
            // iOS only, optional
            album: this.trackToPlay.title,     // optional, default: ''
            duration: this.duration, // optional, default: 0
            elapsed: this.saturation, // optional, default: 0
            // Android only, optional
            ticker: 'Now playing ' + this.trackToPlay.title
        };
        this.musicControls.destroy();
        this.musicControls.create(musicControllOptions)

Is there any other option I have to use for showing notification in background mode?

Environment info:
cli packages:

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1) 

local packages:

    @ionic/app-scripts : 1.1.4
    Cordova Platforms  : android 8.1.0 browser 5.0.4 ios 4.5.5
    Ionic Framework    : ionic-angular 2.3.0

System:

    Android SDK Tools : 26.1.1
    Node              : v10.16.3
    npm               : 6.9.0 
    OS                : Linux 4.15

Misc:

    backend : pro

**Comment by germboy** [comment] 2019-12-27 15:11
I noticed this behavior as well, but it my case, this behavior only happens after introducing another plugin to my project: [phonegap-push-plugin](https://github.com/phonegap/phonegap-plugin-push)

If I remove the phonegap-push-plugin from my project, then my music controls notification will remain when my app is moved to the background. Perhaps you could check if this (or another) plugin is causing this behavior in your project.

I'm not sure which plugin is to blame or how to better diagnose the issue (or even if this is the same issue you're running into), but hopefully this will help someone else/smarter to isolate the actual issue.

**Comment by StaymanHou** [comment] 2020-01-01 00:43
Just ran into the same issue.

Looks like it's related to the behavior mentioned in this [issue in phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push/issues/2772)

**Comment by StaymanHou** [comment] 2020-01-01 01:11
After browsing through part of the push plugin code, I found a solution. Set the `clearNotifications` option to false when initializing the push notification plugin.

Example
```
PushNotification.init({
  android: {
    ...
    clearNotifications: false,
  },
  ios: {
    ...
  },
});
```

Now the music player shouldn't be destroyed when the app moves to background. However, you will now have to write your own code to clear the push notifications. I'll post an issue to the push plugin repo. I believe the expected behavior for that plugin should be clearing only the push notification but should not interfere other notifications.

**Comment by StaymanHou** [comment] 2020-01-01 01:14
It appears that someone's already brought up the issue. And there will be no fix on the push plugin side.

https://github.com/phonegap/phonegap-plugin-push/issues/655

**Comment by ghenry22** [comment] 2020-04-29 02:29
I have forked the push notification plugin and moved the clear all notifications call into onDestroy rather than onPause.

This should mean that all app notifications (including music controls) persist while the app is in the background but will be cleared when the app is killed so they don't create clutter.

Give it a try and see if it helps:
https://github.com/ghenry22/phonegap-plugin-push/tree/fix_clear_on_pause

**Comment by SiberianCMS** [comment] 2020-05-05 09:46
> I have forked the push notification plugin and moved the clear all notifications call into onDestroy rather than onPause.
> 
> This should mean that all app notifications (including music controls) persist while the app is in the background but will be cleared when the app is killed so they don't create clutter.
> 
> Give it a try and see if it helps:
> https://github.com/ghenry22/phonegap-plugin-push/tree/fix_clear_on_pause

Tested it, and works ok for now.

**Comment by ghenry22** [comment] 2020-05-14 03:56
Going to close this as this isn't something I can fix here.  I have created a fork of the push plugin with a fix as above that will help but unless they agree to merge that there isn't much else I can do.

**Closed as completed by ghenry22** 2020-05-14 03:56 UTC
