### ISSUE TITLE
Android 11 feature enhancement

### ISSUE THREAD

**Issue by ShaunBrassell** [ghenry22/cordova-plugin-music-controls2#65] opened 2021-06-09 12:36 UTC
With Android 11, you can have your media notifications automatically coloured and looking really good by simply adding a session token to your MediaStyle. I added this code to mine in your MusicControlsNotification.java file in the createBuilder method:

		//If 5.0 >= use MediaStyle
		if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP){
			int[] args = new int[nbControls];
			for (int i = 0; i < nbControls; ++i) {
				args[i] = i;
			}
			//builder.setStyle(new Notification.MediaStyle().setShowActionsInCompactView(args));

			Notification.MediaStyle style = new MediaStyle();
      		        style.setShowActionsInCompactView(args);
      		        MediaSession session = (MediaSession) this.mediaSessionCompat.getMediaSession();
      		        style.setMediaSession(session.getSessionToken());
			builder.setStyle(style);
		}

**Comment by ghenry22** [comment] 2021-06-12 09:22
I have this working in dev and currently testing, it will be added in the next version

**Comment by ghenry22** [comment] 2021-06-12 09:23
closing as duplicate of #38

**Closed as completed by ghenry22** 2021-06-12 09:23 UTC
